export type Clients = Set<Map<string, string | null>>;

export const headers: Set<string> = new Set([
    'Timestamp',
    'Head of Household First Name',
    'Head of Household Last Name',
    'Head of Household Date of Birth',
    'Head of Household City:',
    'Head of Household Zip code:',
    'Other than the Head of Household, how many people in their/your household?',
    'What size diapers does your baby need?',
    'How much dog food do you need?',
    'I acknowledge',
    'Yes, I have over 10 individuals in my household',
    'Head of Household House Number:',
    'Head of Household Street:',
    'Head of Household APT # (if Applicable):',
    'How many people in your household need gluten free food?',
    'How many people in your household need sugar free food?',
    'How many people in your household need low sodium food?',
    'How many people in your household need alternate milk?',
    'Do you or members of your family not eat...',
    'If yes, what type?',
    'Do You Need Baby Food?',
    'Do You Need Baby Formula?',
    'How much cat food do you need?',
    'Any other dietary/ food choice information you would like us to add to your file:',
    'Do you have a baby and want extra services?',
    'Do you have any pets, if so, do you want any service for them?',
    "1st member's first name",
    "1st member's last name",
    "1st member's age",
    "2nd member's first name",
    "2nd member's last name",
    "2nd member's age",
    "3rd member's first name",
    "3rd member's last name",
    "3rd member's age",
    "4th member's first name",
    "4th member's last name",
    "4th member's age",
    "5th member's first name",
    "5th member's last name",
    "5th member's age",
    "6th member's first name",
    "6th member's last name",
    "6th member's age",
    "7th member's first name",
    "7th member's second name",
    "7th member's age",
    "8th member's first name",
    "8th member's last name",
    "8th member's age",
    "9th member's first name",
    "9th member's last name",
    "9th member's age",
    "10th member's first name",
    "10th member's last name",
    "10th member's age"
]);