export function buildFullGuestPayload(overrides = {}) {
  return {
    firstname: "",
    middlename: "",
    lastname: "",
    dob: "2000-01-01",
    homeless: 0,
    street_address: "",
    apartment: "",
    city: "",
    state: "",
    zipcode: "",
    visit_exception: 0,
    visitor_type: null,
    notes: null,
    dobSet: 1,
    lng: null,
    lat: null,
    noMatch: 0,
    addrUpdated: 0,
    blackball: 0,
    profilePicture: "",
    saveCount: 0,
    household_total: 1,
    othersHousehold: [],
    barcode: "",
    county: "",
    phone: "",
    language: "English",
    gender: "0",
    race: "0",
    incomeTotal: "0.00",
    expenseTotal: "0.00",
    netTotal: "0.00",
    custom1Field: "",
    cf_guests_901d83d3c7: "",
    cf_guests_1fb4745f10: [],
    cf_guests_b70a510d7c: "",
    cf_guests_7d69b8c4d5: [],
    cf_guests_9d6e374e65: "",
    cf_guests_36ccf4ecb9: "",
    cf_guests_ed8edf4e3d: "",
    cf_guests_e22b8fce8e: null,
    cf_guests_24d312b3b6: "",
    cf_guests_45ae5f86e4: "In Country",
    cf_guests_8e6f172090: "Small- 1 to 3",
    cf_guests_e8827ca4cf: null,
    cf_guests_459373e1d1: [],
    ...overrides,
  };
}